version: '3.3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        networks:
            - laravel-net
        ports:
            - "9000:80"
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - APP_KEY=

    db:
        image: mysql:8.0
        container_name: mysql-db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel_db
            MYSQL_USER: laravel_user
            MYSQL_PASSWORD: laravel_pass
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - "4406:3306"
        networks:
            - laravel-net

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: unless-stopped
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "8080:80"
        depends_on:
            - db
        networks:
            - laravel-net

networks:
    laravel-net:

volumes:
    db_data:
